// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA6JCt1rNGQfF_SQMaLsFEx1KVfyZJ5rw',
    appId: '1:281575281632:web:cba5817f6369db659bd185',
    messagingSenderId: '281575281632',
    projectId: 'retohabitos-1b872',
    authDomain: 'retohabitos-1b872.firebaseapp.com',
    storageBucket: 'retohabitos-1b872.firebasestorage.app',
    measurementId: 'G-V1NN1GMW56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSr9itBZnRJyX_cJI2w8tTCy1i2PVlasE',
    appId: '1:281575281632:android:bd8a45dc743e81a89bd185',
    messagingSenderId: '281575281632',
    projectId: 'retohabitos-1b872',
    storageBucket: 'retohabitos-1b872.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-YnyKNmayOdT-8NwsUPD1eZUy-SLXRDk',
    appId: '1:281575281632:ios:c1d605a9a6fbe6519bd185',
    messagingSenderId: '281575281632',
    projectId: 'retohabitos-1b872',
    storageBucket: 'retohabitos-1b872.firebasestorage.app',
    iosBundleId: 'com.example.retoHabitos',
  );

}